package hu.mnb.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-09-08T13:55:50.888+02:00
 * Generated source version: 3.2.7
 * 
 */
@WebServiceClient(name = "MNBArfolyamServiceSoapImpl", 
                  wsdlLocation = "file:/C:/Users/kisadii/Downloads/stockcalculator/src/main/resources/wsdl/arfolyamok.asmx.xml",
                  targetNamespace = "http://www.mnb.hu/webservices/") 
public class MNBArfolyamServiceSoapImpl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.mnb.hu/webservices/", "MNBArfolyamServiceSoapImpl");
    public final static QName CustomBindingMNBArfolyamServiceSoap = new QName("http://www.mnb.hu/webservices/", "CustomBinding_MNBArfolyamServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/kisadii/Downloads/stockcalculator/src/main/resources/wsdl/arfolyamok.asmx.xml");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MNBArfolyamServiceSoapImpl.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/kisadii/Downloads/stockcalculator/src/main/resources/wsdl/arfolyamok.asmx.xml");
        }
        WSDL_LOCATION = url;
    }

    public MNBArfolyamServiceSoapImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MNBArfolyamServiceSoapImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MNBArfolyamServiceSoapImpl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public MNBArfolyamServiceSoapImpl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MNBArfolyamServiceSoapImpl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MNBArfolyamServiceSoapImpl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns MNBArfolyamServiceSoap
     */
    @WebEndpoint(name = "CustomBinding_MNBArfolyamServiceSoap")
    public MNBArfolyamServiceSoap getCustomBindingMNBArfolyamServiceSoap() {
        return super.getPort(CustomBindingMNBArfolyamServiceSoap, MNBArfolyamServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MNBArfolyamServiceSoap
     */
    @WebEndpoint(name = "CustomBinding_MNBArfolyamServiceSoap")
    public MNBArfolyamServiceSoap getCustomBindingMNBArfolyamServiceSoap(WebServiceFeature... features) {
        return super.getPort(CustomBindingMNBArfolyamServiceSoap, MNBArfolyamServiceSoap.class, features);
    }

}
