
package hu.mnb.webservices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-09-08T13:55:50.851+02:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "string", targetNamespace = "http://schemas.microsoft.com/2003/10/Serialization/")
public class MNBArfolyamServiceSoapGetExchangeRatesStringFaultFaultMessage extends Exception {
    
    private java.lang.String string;

    public MNBArfolyamServiceSoapGetExchangeRatesStringFaultFaultMessage() {
        super();
    }
    
    public MNBArfolyamServiceSoapGetExchangeRatesStringFaultFaultMessage(String message) {
        super(message);
    }
    
    public MNBArfolyamServiceSoapGetExchangeRatesStringFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public MNBArfolyamServiceSoapGetExchangeRatesStringFaultFaultMessage(String message, java.lang.String string) {
        super(message);
        this.string = string;
    }

    public MNBArfolyamServiceSoapGetExchangeRatesStringFaultFaultMessage(String message, java.lang.String string, Throwable cause) {
        super(message, cause);
        this.string = string;
    }

    public java.lang.String getFaultInfo() {
        return this.string;
    }
}
