package hu.mnb.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-09-08T13:55:50.857+02:00
 * Generated source version: 3.2.7
 * 
 */
@WebService(targetNamespace = "http://www.mnb.hu/webservices/", name = "MNBArfolyamServiceSoap")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MNBArfolyamServiceSoap {

    @WebMethod(operationName = "GetCurrentExchangeRates", action = "http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRates")
    @Action(input = "http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRates", output = "http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRatesResponse", fault = {@FaultAction(className = MNBArfolyamServiceSoapGetCurrentExchangeRatesStringFaultFaultMessage.class, value = "http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRatesStringFault")})
    @WebResult(name = "GetCurrentExchangeRatesResponse", targetNamespace = "http://www.mnb.hu/webservices/", partName = "GetCurrentExchangeRatesResponse")
    public GetCurrentExchangeRatesResponseBody getCurrentExchangeRates(
        @WebParam(partName = "GetCurrentExchangeRates", name = "GetCurrentExchangeRates", targetNamespace = "http://www.mnb.hu/webservices/")
        GetCurrentExchangeRatesRequestBody getCurrentExchangeRates
    ) throws MNBArfolyamServiceSoapGetCurrentExchangeRatesStringFaultFaultMessage;

    @WebMethod(operationName = "GetCurrencyUnits", action = "http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnits")
    @Action(input = "http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnits", output = "http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnitsResponse", fault = {@FaultAction(className = MNBArfolyamServiceSoapGetCurrencyUnitsStringFaultFaultMessage.class, value = "http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnitsStringFault")})
    @WebResult(name = "GetCurrencyUnitsResponse", targetNamespace = "http://www.mnb.hu/webservices/", partName = "GetCurrencyUnitsResponse")
    public GetCurrencyUnitsResponseBody getCurrencyUnits(
        @WebParam(partName = "GetCurrencyUnits", name = "GetCurrencyUnits", targetNamespace = "http://www.mnb.hu/webservices/")
        GetCurrencyUnitsRequestBody getCurrencyUnits
    ) throws MNBArfolyamServiceSoapGetCurrencyUnitsStringFaultFaultMessage;

    @WebMethod(operationName = "GetCurrencies", action = "http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencies")
    @Action(input = "http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencies", output = "http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrenciesResponse", fault = {@FaultAction(className = MNBArfolyamServiceSoapGetCurrenciesStringFaultFaultMessage.class, value = "http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrenciesStringFault")})
    @WebResult(name = "GetCurrenciesResponse", targetNamespace = "http://www.mnb.hu/webservices/", partName = "GetCurrenciesResponse")
    public GetCurrenciesResponseBody getCurrencies(
        @WebParam(partName = "GetCurrencies", name = "GetCurrencies", targetNamespace = "http://www.mnb.hu/webservices/")
        GetCurrenciesRequestBody getCurrencies
    ) throws MNBArfolyamServiceSoapGetCurrenciesStringFaultFaultMessage;

    @WebMethod(operationName = "GetDateInterval", action = "http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateInterval")
    @Action(input = "http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateInterval", output = "http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateIntervalResponse", fault = {@FaultAction(className = MNBArfolyamServiceSoapGetDateIntervalStringFaultFaultMessage.class, value = "http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateIntervalStringFault")})
    @WebResult(name = "GetDateIntervalResponse", targetNamespace = "http://www.mnb.hu/webservices/", partName = "GetDateIntervalResponse")
    public GetDateIntervalResponseBody getDateInterval(
        @WebParam(partName = "GetDateInterval", name = "GetDateInterval", targetNamespace = "http://www.mnb.hu/webservices/")
        GetDateIntervalRequestBody getDateInterval
    ) throws MNBArfolyamServiceSoapGetDateIntervalStringFaultFaultMessage;

    @WebMethod(operationName = "GetInfo", action = "http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfo")
    @Action(input = "http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfo", output = "http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfoResponse", fault = {@FaultAction(className = MNBArfolyamServiceSoapGetInfoStringFaultFaultMessage.class, value = "http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfoStringFault")})
    @WebResult(name = "GetInfoResponse", targetNamespace = "http://www.mnb.hu/webservices/", partName = "GetInfoResponse")
    public GetInfoResponseBody getInfo(
        @WebParam(partName = "GetInfo", name = "GetInfo", targetNamespace = "http://www.mnb.hu/webservices/")
        GetInfoRequestBody getInfo
    ) throws MNBArfolyamServiceSoapGetInfoStringFaultFaultMessage;

    @WebMethod(operationName = "GetExchangeRates", action = "http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRates")
    @Action(input = "http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRates", output = "http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRatesResponse", fault = {@FaultAction(className = MNBArfolyamServiceSoapGetExchangeRatesStringFaultFaultMessage.class, value = "http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRatesStringFault")})
    @WebResult(name = "GetExchangeRatesResponse", targetNamespace = "http://www.mnb.hu/webservices/", partName = "GetExchangeRatesResponse")
    public GetExchangeRatesResponseBody getExchangeRates(
        @WebParam(partName = "GetExchangeRates", name = "GetExchangeRates", targetNamespace = "http://www.mnb.hu/webservices/")
        GetExchangeRatesRequestBody getExchangeRates
    ) throws MNBArfolyamServiceSoapGetExchangeRatesStringFaultFaultMessage;
}
